config/routes.rb
Rails.application.routes.draw do
  get 'flats/:id', to: 'flats#show', as: :flat
  root to: 'flats#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
require 'open-uri'

class FlatsController < ApplicationController
  FLATS_URL = "https://raw.githubusercontent.com/lewagon/flats-boilerplate/master/flats.json".freeze
  before_action :set_flats

  def show
    @flat = @flats.find { |flat| flat["id"] == params[:id].to_i  }
  end

  def index
  end

  private

  def set_flats
    response_serialized = open(FLATS_URL).read
    # json hash
    @flats = JSON.parse(response_serialized)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/index.html.erb
<div class="wrapper-grey padded">
  <div class="container">
    <h1 class="text-center">Selection of Flats in Paris:</h1>
    <p class="text-center">Rent unique places to stay from local hosts in Paris.</p>
    <div class="row">
     <% @flats.each do |flat| %>
      <div class="col-xs-12 col-sm-4">
        <div class="card" style="background-image: linear-gradient(-225deg, rgba(0,101,168,0.6) 0%, rgba(0,36,61,0.6) 50%), url('https://kitt.lewagon.com/placeholder/cities/paris')">
          <div class="card-category">Paris</div>
          <div class="card-description">
            <%= link_to flat["name"], flat_path(flat["id"]) %>
            <%= flat["price"] %> <%= flat["priceCurrency"] %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>

app/views/flats/show.html.erb
<div class="wrapper-grey padded">
  <div class="container">
    <h1><%= @flat["name"]%></h1>
    <div class="row">
      <div class="col-xs-12 col-sm-4">
        <div class="card">
            <%= image_tag @flat["imageUrl"], alt: @flat["name"], class: "card" %>
          <div class="card-description">
            <h2>Price: <%= @flat["price"]%> <%= @flat["priceCurrency"] %></h2>
          </div>
        </div>
      </div>
    </div>
      <%= link_to 'All Flats', root_path %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Rails Static Airbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.2.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>